# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fecedc948654d3d848512550649341e5ad6e15797d13d80ff6ab3ec15f68baba0126a6a14686eafe9ff965672a02381055fcaa3ecd9eff6e40b311cded2a7d37

test:
  secret_key_base: 9afd3e74d8f94ae3fcbd8980c3ef84aca97da08fc3a1b780f76d9502a68b0f8fd8e504d3317f32d6fc10205be6a53c302aa6810a82d57e7f80dd7b619401f97f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
